add check for /etc/cron.d/auto-reboot enablement

diff --git a/rbc b/rbc
--- a/rbc
+++ b/rbc
@@ -8,6 +8,7 @@ REBOOT_ALLOWED=0
 REBOOT_REQUIRED=0
 SUMMARY=0
 SYSLOG=0
+MANUAL_REBOOT=1
 
 die () {
     printf "Error, exiting: " 1>&2
@@ -28,7 +29,7 @@ usage () {
     printf "   -q: suppress output to STDOUT\n" 1>&2
     printf "   -r: reboot the system in 30 minutes if reboot is required, SYSLOG is forced\n" 1>&2
     printf "   -s: print a one line status summary in CSV, with the following format\n"
-    printf "        hostname, OS release, uptime, RBC status code\n" 1>&2
+    printf "        hostname, OS release, uptime, RBC status code, auto-reboot disabled\n" 1>&2
     printf "   EXIT codes:\n" 1>&2
     printf "%14s %-70s\n" "0:" "reboot not required" 1>&2
     printf "%14s %-70s\n" "1:" "reboot required, kernel only" 1>&2
@@ -123,9 +124,11 @@ if [ $REBOOT_REQUIRED -ne 0 ]; then
 fi
 
 if [ $SUMMARY -eq 1 ] ; then
+    grep '^\s*[0-9].*/usr/local/sbin/rbc -l -r.*$' /etc/cron.d/auto-reboot >/dev/null 2>&1
+    [ $? -eq 0 ] && MANUAL_REBOOT=0
     # get the following the hard way since RHEL 6 uptime does not have the -s flag :(
     UPSINCE=$(date -d @$(( $(date +%s) - $(sed 's|\..*$||' /proc/uptime) )) +%Y-%m-%d\ %H:%M:%S)
-    printf "%s,%s,%s,%s\n" "${HOSTNAME}" "$(cat /etc/redhat-release)" "${UPSINCE}" "${REBOOT_REQUIRED}"
+    printf "%s,%s,%s,%s,%s\n" "${HOSTNAME}" "$(cat /etc/redhat-release)" "${UPSINCE}" "${REBOOT_REQUIRED}" "${MANUAL_REBOOT}"
 fi
 
 exit $REBOOT_REQUIRED
